# Generated by Django 6.0.2 on 2026-02-23 12:28

import custom_auth_system.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', custom_auth_system.users.managers.UserManager()),
            ],
        ),
    ]
